config/routes.rb
Rails.application.routes.draw do
  resources :flashcard_sets
  get 'flashcard_sets/:id/quiz' => 'flashcard_sets#quiz'

  devise_for :users
  root 'flashcards#index'

  resources :flashcards

end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
	validates :question, presence: true
	validates :answer, presence: true

  belongs_to :flashcard_set
end

app/models/flashcard_set.rb
class FlashcardSet < ActiveRecord::Base
  validates :title, presence: true
  
  has_many :flashcards
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/flashcard_sets_controller.rb
class FlashcardSetsController < ApplicationController
  before_action :set_flashcard_set, only: [:quiz, :show, :edit, :update, :destroy]

  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcard_sets = FlashcardSet.all
  end

  # GET /flashcard_sets/1/quiz
  def quiz
  end

  # GET /flashcard_sets/1
  # GET /flashcard_sets/1.json
  def show
  end

  # GET /flashcard_sets/new
  def new
    @flashcard_set = FlashcardSet.new
  end

  # GET /flashcard_sets/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard_set = FlashcardSet.new(flashcard_set_params)

    respond_to do |format|
      if @flashcard_set.save
        format.html { redirect_to @flashcard_set, notice: 'FlashcardSet was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard_set }
      else
        format.html { render :new }
        format.json { render json: @flashcard_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard_set.update(flashcard_set_params)
        format.html { redirect_to @flashcard_set, notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard_set }
      else
        format.html { render :edit }
        format.json { render json: @flashcard_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard_set.destroy
    respond_to do |format|
      format.html { redirect_to flashcard_sets_url, notice: 'FlashcardSet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flashcard_set
    @flashcard_set = FlashcardSet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flashcard_set_params
    params.require(:flashcard_set).permit(:title)
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]

  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcards = Flashcard.all
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
  end

  # GET /flashcards/new
  def new
    @flashcard = Flashcard.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard = Flashcard.new(flashcard_params)

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'Flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flashcard_params
      params.require(:flashcard).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcard_sets_helper.rb
module FlashcardSetsHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/flashcard_sets/_form.html.haml
= form_for @flashcard_set, html: { class: "form form-horizontal flashcard_set" } do |f|
  .form-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'form-control', required: true
    = error_span(@flashcard_set[:title])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), flashcard_sets_path, :class => 'btn btn-default'

app/views/flashcard_sets/edit.html.haml
- model_class = FlashcardSet
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flashcard_sets/index.html.haml
- model_class = FlashcardSet
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @flashcard_sets.each do |flashcard_set|
      %tr
        %td= link_to flashcard_set.id, flashcard_set_path(flashcard_set)
        %td= flashcard_set.title
        %td=l flashcard_set.created_at
        %td
          = link_to "quiz", "/flashcard_sets/#{flashcard_set.id}/quiz", :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_flashcard_set_path(flashcard_set), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), flashcard_set_path(flashcard_set), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_flashcard_set_path, :class => 'btn btn-primary'

app/views/flashcard_sets/new.html.haml
- model_class = FlashcardSet
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flashcard_sets/quiz.html.haml
%h1
  = @flashcard_set.title

#quizContainer
  .panel.panel-primary
    .panel-heading
      %h1{:style => "text-align:center;"}
        %a#question{:style => "color:#fff;", :data => {:toggle=>"collapse", :target=>"#collapseAnswer"}, :aria => {:expanded=>"true", :controls=>"demo"}}
    #collapseAnswer.panel-collapse.collapse
      .panel-body
        %h1#answer{:style => "text-align:center;"}
        %div{:style => "text-align:center;"}
          %a.btn.btn-danger.btn-lg#false
            %span.glyphicon.glyphicon-remove{:aria => {:hidden => "true"}}
          %a.btn.btn-success.btn-lg#true
            %span.glyphicon.glyphicon-ok{:aria => {:hidden => "true"}}


:javascript
  $(document).ready(function() {
    var quizJSON = #{
      a = @flashcard_set.flashcards.to_a.map {|x| '{"question":"'+x.question.to_s + '","' + 'answer":"' + x.answer.to_s+'"}'}
      "[" + a.join(",") + "]"
    }
    var quiz = new FlashcardsQuiz(quizJSON, $('#quizContainer'), $("#question"), $("#answer"), $("#true"), $("#false"));
    quiz.show();
  });

app/views/flashcard_sets/show.html.haml
- model_class = FlashcardSet
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @flashcard_set.title

= link_to "Quiz", "/flashcard_sets/#{@flashcard_set.id}/quiz", :class => 'btn btn-primary'
= link_to t('.back', :default => t("helpers.links.back")), flashcard_sets_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_flashcard_set_path(@flashcard_set), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), flashcard_set_path(@flashcard_set), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/flashcards/_form.html.haml
= form_for @flashcard, html: { class: "form form-horizontal flashcard" } do |f|
	-if @flashcard.errors.any?
		#error_explanation
			%h2
				=pluralize(@flashcard.errors.count, "error")
				prohibited this post from being saved:
	 
			%ul
				-@flashcard.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.label :question, class: 'control-label'
	.controls
		= f.text_field :question, class: 'form-control'
		= error_span(@flashcard[:question])
	.form-group
		= f.label :answer, class: 'control-label'
	.controls
		= f.text_field :answer, class: 'form-control'
	= error_span(@flashcard[:answer])
	= f.submit nil,class: 'btn btn-primary'
	= link_to t('.cancel', :default => t("helpers.links.cancel")), flashcards_path, :class => 'btn btn-default'

app/views/flashcards/edit.html.haml
- model_class = Flashcard
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flashcards/index.html.haml
- model_class = Flashcard
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:question)
      %th= model_class.human_attribute_name(:answer)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @flashcards.each do |flashcard|
      %tr
        %td= link_to flashcard.id, flashcard_path(flashcard)
        %td= flashcard.question
        %td= flashcard.answer
        %td=l flashcard.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_flashcard_path(flashcard), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), flashcard_path(flashcard), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_flashcard_path, :class => 'btn btn-primary'

app/views/flashcards/new.html.haml
- model_class = Flashcard
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/flashcards/show.html.haml
- model_class = Flashcard
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:question) + ':'
  %br
  = @flashcard.question
%p
  %strong= model_class.human_attribute_name(:answer) + ':'
  %br
  = @flashcard.answer


= link_to t('.back', :default => t("helpers.links.back")), flashcards_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_flashcard_path(@flashcard), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), flashcard_path(@flashcard), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fiszki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>